### ISSUE TITLE
Error when creating and diagnosing designs within functional environments

### ISSUE THREAD

**Issue by jaspercooper** [DeclareDesign/DeclareDesign#26] opened 2017-09-07 16:35 UTC
In the code below, if you define the arguments and run everything within the { } of `stepped_wedge_design` everything runs fine. However, when you declare the function as below and then try to run it (i.e. `diagnosis <- stepped_wedge_design()`), you get the following error: 

> ` Error in { : task 1 failed - "object 'current_df' not found" `

So clearly somethings breaking in `declare_design()` when using custom functions within another function's environment. 

MWE:

```r
stepped_wedge_design <- function(
	N_cells = 550,
	prop_eligible = .70,
	implementation_start = as.Date("2018-03-01"),
	implementation_spacing = 90,
	burn_in_months = 12,
	theta = -.5,
	epsilon = .1,
	psi = .1,
	alpha_range = c(3.1,4.1),
	rho = 0,
	wave_assignment_probs = rep(1,4)/4,
	sims = 10
){
	
	N_eligible <- round(N_cells*prop_eligible)
	
	# Check here for negative lambdas
	
	implementation_waves <- implementation_start
	for(i in 1:(3 - 1)){
		implementation_waves <- c(implementation_waves,implementation_waves[i] + implementation_spacing)
	}
	survey_dates <- implementation_start - 30
	for(i in 1:length(implementation_waves)){
		survey_dates <- c(survey_dates,implementation_waves[i] + c(30,60))
	}
	for(i in 1:burn_in_months){
		survey_dates <- c(implementation_start - 30*i,survey_dates)
	}
	population <- declare_population(
		# There are 9 non-nested levels: survey dates
		dates = level(
			N = length(survey_dates), 
			date = survey_dates,
			period = 1:length(survey_dates),
			linear_days = date - min(survey_dates), 
			period_shock = runif(N,-psi,psi) # psi_t
		),
		# At each survey date, there are 550 cells about which we 
		# collect information
		cells = level(
			N = N_cells, 
			cell_id = 1:N_cells, 
			unit_shock = ave(runif(N,alpha_range[1],alpha_range[2]),cell_id), # alpha_i
			unit_period_shock = runif(N,-epsilon,epsilon), # epsilon_it
			effect_size = theta # theta
		)
	)
	
	assignment <- declare_assignment(
		clust_var = cell_id,
		prob_each = c(
			1 - prop_eligible,
			prop_eligible * wave_assignment_probs),
		condition_names = c("NE","W0","W1","W2","W3"),
		assignment_variable_name = "Z"
	)
	
	days_treated <- function(data){
		data$days_treated <- NA
		data$days_treated[data$Z == "NE"] <- 0
		data$days_treated[data$Z == "W0"] <- 0
		data$days_treated[data$Z == "W1"] <- data$date[data$Z == "W1"] - implementation_waves[1]
		data$days_treated[data$Z == "W2"] <- data$date[data$Z == "W2"] - implementation_waves[2] 
		data$days_treated[data$Z == "W3"] <- data$date[data$Z == "W3"] - implementation_waves[3]
		data$days_treated[data$days_treated < 0] <- 0
		
		data$thirty_days <- as.numeric(data$days_treated == 30)
		
		counts <- data %>% 
			group_by(Z) %>% 
			summarize(n = length(unique(cell_id)))
		
		prob_0_W1 <- with(counts,sum(n[!Z  %in% c("NE","W1")])/sum(n[!Z  %in% c("NE")]))
		prob_30_W1 <- with(counts,sum(n[Z == "W1"])/sum(n[!Z  %in% c("NE")]))
		
		# prob of being assigned to control in 1st * prob of being assigned to control in 2nd
		prob_0_W2 <- with(counts,sum(n[!Z  %in% c("NE","W1","W2")])/sum(n[!Z  %in% c("NE","W1")]))*prob_0_W1
		prob_30_W2 <- with(counts,sum(n[Z == "W2"])/sum(n[!Z  %in% c("NE","W1")]))*prob_0_W1
		
		prob_0_W3 <- with(counts,sum(n[!Z  %in% c("NE","W1","W2","W3")])/sum(n[!Z  %in% c("NE","W1","W2")]))*prob_0_W2
		prob_30_W3 <- with(counts,sum(n[Z == "W3"])/sum(n[!Z  %in% c("NE","W1","W2")]))*prob_0_W2
		
		
		data$thirty_days_cond_prob <- NA
		data$thirty_days_cond_prob[data$Z == "W1" & data$thirty_days == 0] <- prob_0_W1
		data$thirty_days_cond_prob[data$Z == "W1" & data$thirty_days == 1] <- prob_30_W1
		data$thirty_days_cond_prob[data$Z == "W2" & data$thirty_days == 0] <- prob_0_W2
		data$thirty_days_cond_prob[data$Z == "W2" & data$thirty_days == 1] <- prob_30_W2
		data$thirty_days_cond_prob[data$Z == "W3" & data$thirty_days == 0] <- prob_0_W3
		data$thirty_days_cond_prob[data$Z == "W3" & data$thirty_days == 1] <- prob_30_W3
		data$thirty_days_cond_prob[data$Z == "W0" & data$thirty_days == 0] <- prob_0_W3
		
		data$days_treated_NE <- 0
		data$days_treated_W0 <- 0
		data$days_treated_W1 <- data$date - implementation_waves[1]
		data$days_treated_W1[data$days_treated_W1 < 0] <- 0
		data$days_treated_W2 <- data$date - implementation_waves[2]
		data$days_treated_W2[data$days_treated_W2 < 0] <- 0
		data$days_treated_W3 <- data$date - implementation_waves[3]
		data$days_treated_W3[data$days_treated_W3 < 0] <- 0
		
		return(data)
	}
	
	potential_treatments <- declare_potential_outcomes(
		wave_NE = 0,
		wave_0 = 0,
		wave_1 = as.numeric(date >= implementation_waves[1]),
		wave_2 = as.numeric(date >= implementation_waves[2]),
		wave_3 = as.numeric(date >= implementation_waves[3])
	)
	
	potential_outcomes <- declare_potential_outcomes(
		potential_outcomes_function = function(data,rho){
			data$Y_Z_NE <- data$Y_Z_W0 <- data$Y_Z_W1 <- data$Y_Z_W2 <- data$Y_Z_W3 <- NA
			data$Y_Z_NE[data$period == 1] <- 
				with(data[data$period == 1,],unit_shock + period_shock + unit_period_shock + effect_size * wave_NE)
			data$Y_Z_W0[data$period == 1] <- 
				with(data[data$period == 1,],unit_shock + period_shock + unit_period_shock + effect_size * wave_0)
			data$Y_Z_W1[data$period == 1] <- 
				with(data[data$period == 1,],unit_shock + period_shock + unit_period_shock + effect_size * wave_1)
			data$Y_Z_W2[data$period == 1] <- 
				with(data[data$period == 1,],unit_shock + period_shock + unit_period_shock + effect_size * wave_2)
			data$Y_Z_W3[data$period == 1] <- 
				with(data[data$period == 1,],unit_shock + period_shock + unit_period_shock + effect_size * wave_3)
			
			for(i in 2:length(survey_dates)){
				data$Y_Z_NE[data$period == i] <- 
					with(data[data$period == i,],unit_shock + period_shock + unit_period_shock + effect_size * wave_NE + 
							 	data$Y_Z_NE[data$period == i-1] * rho
					)
				data$Y_Z_W0[data$period == i] <- 
					with(data[data$period == i,],unit_shock + period_shock + unit_period_shock + effect_size * wave_0 + 
							 	data$Y_Z_W0[data$period == i-1] * rho
					)
				data$Y_Z_W1[data$period == i] <- 
					with(data[data$period == i,],unit_shock + period_shock + unit_period_shock + effect_size * wave_1 + 
							 	data$Y_Z_W1[data$period == i-1] * rho
					)
				data$Y_Z_W2[data$period == i] <- 
					with(data[data$period == i,],unit_shock + period_shock + unit_period_shock + effect_size * wave_2 + 
							 	data$Y_Z_W2[data$period == i-1] * rho
					)
				data$Y_Z_W3[data$period == i] <- 
					with(data[data$period == i,],unit_shock + period_shock + unit_period_shock + effect_size * wave_3 + 
							 	data$Y_Z_W3[data$period == i-1] * rho
					)
			}
			
			data$Y_Z_NE_lambda <- data$Y_Z_NE
			data$Y_Z_NE <- rpois(nrow(data),data$Y_Z_NE)
			data$Y_Z_W0_lambda <- data$Y_Z_W0
			data$Y_Z_W0 <- rpois(nrow(data),data$Y_Z_W0)
			data$Y_Z_W1_lambda <- data$Y_Z_W1
			data$Y_Z_W1 <- rpois(nrow(data),data$Y_Z_W1)
			data$Y_Z_W2_lambda <- data$Y_Z_W2
			data$Y_Z_W2 <- rpois(nrow(data),data$Y_Z_W2)
			data$Y_Z_W3_lambda <- data$Y_Z_W3
			data$Y_Z_W3 <- rpois(nrow(data),data$Y_Z_W3)
			
			data$rho <- rho
			
			return(data)
		},
		rho = rho
	)
	
	
	reveal_outcomes2 <- function(data){
		data$Y <- NA
		data$Y[data$Z == "NE"] <- data$Y_Z_NE[data$Z == "NE"]
		data$Y[data$Z == "W0"] <- data$Y_Z_W0[data$Z == "W0"]
		data$Y[data$Z == "W1"] <- data$Y_Z_W1[data$Z == "W1"]
		data$Y[data$Z == "W2"] <- data$Y_Z_W2[data$Z == "W2"]
		data$Y[data$Z == "W3"] <- data$Y_Z_W3[data$Z == "W3"]
		
		data$Y_lambda <- NA
		data$Y_lambda[data$Z == "NE"] <- data$Y_Z_NE_lambda[data$Z == "NE"]
		data$Y_lambda[data$Z == "W0"] <- data$Y_Z_W0_lambda[data$Z == "W0"]
		data$Y_lambda[data$Z == "W1"] <- data$Y_Z_W1_lambda[data$Z == "W1"]
		data$Y_lambda[data$Z == "W2"] <- data$Y_Z_W2_lambda[data$Z == "W2"]
		data$Y_lambda[data$Z == "W3"] <- data$Y_Z_W3_lambda[data$Z == "W3"]
		return(data)
	}
	
	estimand_30_days <- declare_estimand(
		sate_30_days = mean(c(
			# Any time in which a cell had thirty days of treatment
			mean(Y_Z_W1_lambda[Z != "NE" & days_treated_W1 == 30] -
					 	Y_Z_W0_lambda[Z != "NE" & days_treated_W1 == 30]),
			mean(Y_Z_W2_lambda[Z != "NE" & days_treated_W2 == 30] -
					 	Y_Z_W0_lambda[Z != "NE" & days_treated_W2 == 30]),
			mean(Y_Z_W3_lambda[Z != "NE" & days_treated_W3 == 30] -
					 	Y_Z_W0_lambda[Z != "NE" & days_treated_W3 == 30])
		))
	)
	
	
	estimator_30_days <- declare_estimator(
		estimator_function = function(data){
			
			eligible_data <- subset(data,Z != "NE")
			fit_data <- subset(eligible_data,(days_treated == 0 | days_treated == 30) & date > implementation_start)
			
			the_fit <- lm(
				formula = Y ~ thirty_days + as.factor(period),
				weights = 1/thirty_days_cond_prob,
				fit_data
			)
			
			# vcov_mat <- multiwayvcov::cluster.vcov(model = the_fit,cluster = fit_data$cell_id)
			
			coefs <- summary(the_fit)$coefficients
			cis <- confint(the_fit)
			
			data.frame(
				est = coefs["thirty_days","Estimate"],
				# se = sqrt(diag(vcov_mat)["thirty_days"]),
				se = coefs["thirty_days","Std. Error"],
				p = coefs["thirty_days","Pr(>|t|)"],
				ci_lower = cis["thirty_days","2.5 %"],
				ci_upper = cis["thirty_days","97.5 %"],
				df = the_fit$df.residual
			)
			
		},
		estimand = estimand_30_days,
		label = "estimator_30_days"
	)
	
	
	stepped_design <- declare_design(
		population,
		assignment,
		days_treated,
		potential_treatments,
		potential_outcomes,
		reveal_outcomes2,
		estimand_30_days,
		estimator_30_days
	)
	
	
	diagnosis <- diagnose_design(stepped_design,sims = sims,bootstrap = F)$diagnosands
	
	data <- draw_data(stepped_design)
	
	diagnosis$sd_Y <- sd(subset(data,Z == "W0" & (days_treated_W1 == 30|days_treated_W2 == 30|days_treated_W3 == 30))$Y)
	diagnosis$rho <- rho
	diagnosis$alpha_min <- alpha_range[1]
	diagnosis$alpha_max <- alpha_range[2]
	diagnosis$psi <- psi
	diagnosis$epsilon <- epsilon
	diagnosis$theta <- theta
	diagnosis$cohen_d <- diagnosis$theta / diagnosis$sd_Y
	
	return(diagnosis)
	
} # end of template 
```

**Comment by acoppock** [comment] 2017-09-07 16:37
Very interesting example — thanks.  I wouldn’t *exactly* describe this as a “minimum” working example… can you cut it down to the barebones that don’t work so it’s easier to debug?

**Comment by jaspercooper** [comment] 2017-09-07 16:55
OK I did some Nolan-level `debugonce()` inceptioning and found where the problem arises: it happens when you give a second level in fabricatr some argument passed from the template function:

```r
# This doesn't break:
rm(list = ls())

my_template <- function(
	some_parameter = 2
){
	population <- declare_population(
		a_level = add_level(N = some_parameter,id = 1:some_parameter)
	)
	design <- declare_design(
		population
	)
	draw_data(design)
}

my_template()


# This breaks:
rm(list = ls())

my_template <- function(
	some_parameter = 2,
	some_other_parameter = 3
){
	population <- declare_population(
		a_level = add_level(N = some_parameter,id = 1:some_parameter),
		another_level = add_level(N = some_other_parameter,id_2 = 1:some_other_parameter)
		)
	design <- declare_design(
		population
	)
	draw_data(design)
}

my_template()

```

**Comment by nfultz** [comment] 2018-01-18 23:49
This is happening because `N` is being NSE'd differently from the rest of `...` - should be a straightforward fix @aaronrudkin .

**Comment by graemeblair** [comment] 2018-02-17 05:10
paging @aaronrudkin on this

**Comment by nfultz** [comment] 2018-02-21 16:14
Fixed via rlang:

```r
population <- declare_population(
  a_level = add_level(N = !!some_parameter,id = 1:!!some_parameter),
  another_level = add_level(N = !!some_other_parameter,id_2 = 1:!!some_other_param
)
```

**Closed as completed by nfultz** 2018-02-21 16:14 UTC

**Comment by aaronrudkin** [comment] 2018-02-21 17:55
I was not subscribed to notifications on DD proper, sorry about this -- and yes, Neal is correct, the issue is that the N evaluation didn't inherit the parent environment the way you might have thought it would. Neal's solution will work for now, and I'll take a look at trying to make it work the way you would expect it to.

**Comment by graemeblair** [comment] 2018-02-21 17:58
This solution seems good, but a simpler non-NSE does work for the upper level so too bad it doesn't also work at levels beyond that. Thanks for looking into, @aaronrudkin.

**Comment by aaronrudkin** [comment] 2018-02-21 20:47
I think it's specifically related to the way add_level passes through to nest_level and which parent frame environment is being used. I'm opening an issue on fabricatr in a few minutes.
