### ISSUE TITLE
expand_design does not work with single value

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DeclareDesign#193] opened 2018-06-02 14:36 UTC
Works

```
vary_n <- expand_design(simple_two_arm_designer, N = c(30, 100, 10))
```

Does not work:
```
vary_n <- expand_design(simple_two_arm_designer, N = 30)
```

**Comment by nfultz** [comment] 2018-06-02 14:42
duplicate of #188

**Closed as completed by nfultz** 2018-06-02 14:42 UTC
