### ISSUE TITLE
get_estimates with data argument

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/DeclareDesign#62] opened 2017-11-27 21:09 UTC
We lost the ability in the recent rewrite to be able to get estimates from the design given a new data frame of data -- i.e. if you run the study and you get data back, it'd be nice to take the design and run the estimates. 

```
get_estimates(design = my_design, data = my_study_data)
```

Given that you can already do this by doing

```
my_estimator <- declare_estimator(...)
my_estimator(my_study_data)
```

The advantage is portability of the design object alone. But the problem is we need a way to tell it which estimator you want. By default, it could draw all of the estimators on the new data.

**Comment by graemeblair** [comment] 2018-02-21 05:55
How about this, more general than estimates, just takes data and runs a given step:

`conduct_step(data, design = my_design, step = name_of_step)`

parallel with the new `conduct_design`

**Comment by graemeblair** [comment] 2018-02-21 21:14
Macartan and I were discussing the following additional option for `get_estimates` (or switch to a generic that takes data or a design, Neal will have an informed preference):

`get_estimates(data, design = my_design)`

This tries to run all the estimates from the design given the data you provide and will error if some variable is missing.

So `get_estimates` can either be run on data and a design or a design only.

**Comment by aaronrudkin** [comment] 2018-03-09 19:51
My #132 was unknowingly a dupe of this issue coming at it from a different angle, so let me just add a voice to the chorus saying I think it'd be useful to have a quick way to run `get_estimates()` and either return the data it drew, or inject pre-drawn data.

**Closed as completed** 2018-04-04 15:11 UTC
